version: 2

project_name: yar

builds:
  - id: yar
    builder: rust
    binary: yar
    command: zigbuild
    flags:
      - --release
      - -p=yar-cli
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
    hooks:
      pre:
        - cmd: ./scripts/build-release-runtime.sh {{ .Target }}
          output: true

archives:
  - id: yar
    ids:
      - yar
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "dist/runtime/{{ .Target }}/libyar_runtime.a"
        dst: libyar_runtime.a
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
