use std::fmt;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Kind {
    Illegal,
    Eof,
    Ident,
    Int,
    String,
    Char,
    Assign,
    Colon,
    ColonAssign,
    Semicolon,
    Bang,
    Question,
    Comma,
    Dot,
    Amp,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Pipe,
    AmpAmp,
    PipePipe,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    EqualEqual,
    BangEqual,
    Package,
    Import,
    Fn,
    Pub,
    Let,
    Var,
    Struct,
    Interface,
    Enum,
    Or,
    If,
    Else,
    For,
    Break,
    Continue,
    Return,
    Match,
    Case,
    Taskgroup,
    Spawn,
    True,
    False,
    Nil,
    Error,
    Map,
    Chan,
}

impl fmt::Display for Kind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = match self {
            Kind::Illegal => "illegal",
            Kind::Eof => "eof",
            Kind::Ident => "identifier",
            Kind::Int => "integer",
            Kind::String => "string",
            Kind::Char => "character",
            Kind::Assign => "=",
            Kind::Colon => ":",
            Kind::ColonAssign => ":=",
            Kind::Semicolon => ";",
            Kind::Bang => "!",
            Kind::Question => "?",
            Kind::Comma => ",",
            Kind::Dot => ".",
            Kind::Amp => "&",
            Kind::LParen => "(",
            Kind::RParen => ")",
            Kind::LBrace => "{",
            Kind::RBrace => "}",
            Kind::LBracket => "[",
            Kind::RBracket => "]",
            Kind::Pipe => "|",
            Kind::AmpAmp => "&&",
            Kind::PipePipe => "||",
            Kind::Plus => "+",
            Kind::Minus => "-",
            Kind::Star => "*",
            Kind::Slash => "/",
            Kind::Percent => "%",
            Kind::PlusAssign => "+=",
            Kind::MinusAssign => "-=",
            Kind::StarAssign => "*=",
            Kind::SlashAssign => "/=",
            Kind::PercentAssign => "%=",
            Kind::Less => "<",
            Kind::LessEqual => "<=",
            Kind::Greater => ">",
            Kind::GreaterEqual => ">=",
            Kind::EqualEqual => "==",
            Kind::BangEqual => "!=",
            Kind::Package => "package",
            Kind::Import => "import",
            Kind::Fn => "fn",
            Kind::Pub => "pub",
            Kind::Let => "let",
            Kind::Var => "var",
            Kind::Struct => "struct",
            Kind::Interface => "interface",
            Kind::Enum => "enum",
            Kind::Or => "or",
            Kind::If => "if",
            Kind::Else => "else",
            Kind::For => "for",
            Kind::Break => "break",
            Kind::Continue => "continue",
            Kind::Return => "return",
            Kind::Match => "match",
            Kind::Case => "case",
            Kind::Taskgroup => "taskgroup",
            Kind::Spawn => "spawn",
            Kind::True => "true",
            Kind::False => "false",
            Kind::Nil => "nil",
            Kind::Error => "error",
            Kind::Map => "map",
            Kind::Chan => "chan",
        };
        f.write_str(text)
    }
}

pub fn compound_assign_op(kind: Kind) -> Option<Kind> {
    match kind {
        Kind::PlusAssign => Some(Kind::Plus),
        Kind::MinusAssign => Some(Kind::Minus),
        Kind::StarAssign => Some(Kind::Star),
        Kind::SlashAssign => Some(Kind::Slash),
        Kind::PercentAssign => Some(Kind::Percent),
        _ => None,
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Position {
    pub file: String,
    pub line: usize,
    pub column: usize,
}

impl fmt::Display for Position {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{}", self.line, self.column)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
    pub kind: Kind,
    pub text: String,
    pub pos: Position,
}
